training_episodes: 1000
test_episodes: 300
render: True
learning_rate: 0.003
discount_factor: 0.99
eps: 1.0
eps_dec: 0.0001
eps_min: 0.001
batch_size: 64
replace_target_network_cntr: 100
fc1_dims: 256
fc2_dims: 256
mem_size: 100000
disappointing_score : -100
disappointing_keep_going_ratio : 0.5
env_name: "LunarLander-v2"
