training_episodes: 2000
test_episodes: 300
render: false
learning_rate: 0.00001
discount_factor: 0.99 # gamma
eps: 1.0
eps_dec: 0.000006
eps_min: 0.1
batch_size: 100
replace_target_network_cntr: 160
fc1_dims: 256
fc2_dims: 256
mem_size: 1024


disappointing_time : 30 # 超时时间
disappointing_score : 90
disappointing_keep_going_ratio : 0.8
disappointing_keep_going_max_count : 200

test_predict_model_suffix_name: None
#env_name: "CartPole-v1"
env_name: "LunarLander-v2"