training_episodes: 100
test_episodes: 300
render: False
learning_rate: 0.001
discount_factor: 0.8 # gamma
eps: 1.0
eps_dec: 0.0001
eps_min: 0.1
batch_size: 128
replace_target_network_cntr: 100
fc1_dims: 256
fc2_dims: 256
mem_size: 100000
disappointing_score : 10
disappointing_keep_going_ratio : 0.8
disappointing_keep_going_max_count : 20
env_name: "LunarLander-v2"
