#training_episodes: 500
#test_episodes: 300
#render: False
#learning_rate: 0.003
#discount_factor: 0.99
#eps: 1.0
#eps_dec: 0.0001
#eps_min: 0.01
#batch_size: 64
#replace_target_network_cntr: 100
#fc1_dims: 256
#fc2_dims: 256
#mem_size: 100000
#env_name: "CartPole-v1"



training_episodes: 2000
test_episodes: 300
render: False
learning_rate: 0.003
discount_factor: 0.99 # gamma
eps: 1
eps_dec: 0.0001
eps_min: 0.01
batch_size: 64
replace_target_network_cntr: 100
fc1_dims: 32  
fc2_dims1: 256
fc2_dims2: 64
mem_size: 100000


disappointing_time : 1.1 # 超时时间
disappointing_score : 60
disappointing_keep_going_ratio : 0.9
disappointing_keep_going_max_count : 100

test_predict_model_suffix_name:
#env_name: "CartPole-v1"
env_name: "LunarLander-v2"