version: 1

formatters:
  simple:
    format: "%(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

loggers:
  train:
    level: INFO
    handlers: [console]
    propagate: yes

  test:
    level: INFO
    handlers: [console]
    propagate: yes